version: 1

update_configs:

  - package_manager: "terraform"
    directory: "/{{cookiecutter.module_name}}"
    update_schedule: "daily"

  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
